language: rust
rust: nightly-2019-05-09
cache: cargo

matrix:
  include:
  - name: check
    before_script:
    - rustup component add rustfmt clippy
    script:
    - cargo fmt --all -- --check
    - cargo clippy --all -- -D clippy::all
  - name: test
    script:
    - cargo test --all --all-features --verbose
    - cd openapi/tests/test_k8s && cargo build
