language: rust
rust: nightly-2019-08-23
cache: cargo
node_js: "12"
install: "npm install -g gitbook-cli"

before_script:
- cargo install cargo-sweep --force
- cargo sweep --stamp

before_cache:
- cargo sweep --file

matrix:
  include:
  - name: check
    env:
    - CACHE_NAME=check
    before_script:
    - rustup component add rustfmt clippy
    script:
    - cargo fmt --all -- --check
    - cargo clippy --all -- -D clippy::all
  - name: build
    env:
    - CACHE_NAME=build
    script:
    - cargo build
    - cargo build --features v2
    - cargo build --features default
    - cargo build --features actix
    - cargo build --features cli
    - cargo build --all --all-features
  - name: test
    env:
    - CACHE_NAME=test
    script:
    - cargo test --all --all-features
    - cd tests/test_k8s && cargo check
    - cd ../test_pet && cargo check
    - cd cli && CARGO_TARGET_DIR=../target cargo check
    - cd ../../test_k8s/cli && CARGO_TARGET_DIR=../target cargo build
    - ../target/debug/test-k8s-cli --help > /dev/null
  - name: docs
    env:
    - CACHE_NAME=docs
    script:
    - rm -rf target/doc
    - cargo doc --all --all-features --no-deps
    - gitbook build book/
    - cp -r book/_book/* target/doc/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    condition: "$TRAVIS_JOB_NAME = docs"
  local_dir: target/doc
  fqdn: paperclip.waffles.space
