language: rust
rust: nightly-2019-05-09
cache: cargo

matrix:
  include:
  - name: check
    before_script:
    - rustup component add rustfmt clippy
    script:
    - cargo fmt --all -- --check
    - cargo clippy --all -- -D clippy::all
  - name: test
    script:
    - cargo test --all --all-features --verbose
    - cargo doc --all --all-features --no-deps
    - cd openapi/tests/test_k8s && cargo build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: target/doc
  fqdn: paperclip.waffles.space
