language: rust
rust: nightly-2019-06-09
cache: cargo

before_script:
- cargo install cargo-sweep --force
- cargo sweep --stamp

before_cache:
- cargo sweep --file

matrix:
  include:
  - name: check
    env:
    - CACHE_NAME=check
    before_script:
    - rustup component add rustfmt clippy
    script:
    - cargo fmt --all -- --check
    - cargo clippy --all -- -D clippy::all
  - name: build
    env:
    - CACHE_NAME=build
    script:
    - cargo build
    - cargo build --features default
    - cargo build --all --all-features
  - name: test
    env:
    - CACHE_NAME=test
    script:
    - cargo test --all --all-features
    - rm -rf target/doc
    - cargo doc --all --all-features --no-deps
    - cd openapi/tests/test_k8s
    - cargo build
    - cargo doc --all --all-features --no-deps
    - cd -
    - cp -r openapi/tests/test_k8s/target/doc target/doc/tests
    - cd openapi/tests/test_pet
    - cargo build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    condition: "$TRAVIS_JOB_NAME = test"
  local_dir: target/doc
  fqdn: paperclip.waffles.space
