[package]
name = "paperclip-core"
version = "0.1.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]
edition = "2018"
description = "Core types and traits for paperclip OpenAPI tooling library"
documentation = "https://paperclip.waffles.space/paperclip_core"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/wafflespeanut/paperclip"
repository = "https://github.com/wafflespeanut/paperclip"

[dependencies]
actix-http = { version = "0.2.6", optional = true }
failure = "0.1"
lazy_static = "1.3"
log = "0.4"
paperclip-macros = { path = "../macros", version = "0.2.0" }
parking_lot = "0.9"
regex = "1.1"
serde = "1.0"

[features]
actix = ["default", "actix-http"]
default = ["v2"]
v2 = ["paperclip-macros/v2"]
